sequenceDiagram
    participant Seller
    participant Buyer
    participant MatchOrderFormUI
    participant MarketUI
    participant EOA
    participant MarketSmartContract
    Buyer->>MarketUI :購入したいNFTを選択
    MarketUI->>MatchOrderFormUI: 購入ページに切り替え
    MatchOrderFormUI->>Buyer: 購入ページの表示
    Buyer->>Buyer: 購入ボタン押下
    Buyer->>MatchOrderFormUI: 購入処理呼び出し
    MatchOrderFormUI->>EOA: 購入情報送信
    EOA->>MarketSmartContract: 購入申請 matchOrder(購入情報)
    MarketSmartContract->>MarketSmartContract: 購入処理
    alt revert(NFTの価格>コントラクトに使用許可する金額)
        MarketSmartContract-->>MatchOrderFormUI: 許可金不足通知
        MatchOrderFormUI-->>Buyer: 許可金不足通知
    else
        alt 現在時刻>=締め切り時間
                MarketSmartContract-->>MatchOrderFormUI:締切が過ぎている通知
                MatchOrderFormUI-->>Buyer: 締切が過ぎている通知
        else
                alt 
                    MarketSmartContract-->>MatchOrderFormUI: 所持金不足通知
                    MatchOrderFormUI-->>Seller: 所持金不足通知
                else
                    MarketSmartContract->>MarketSmartContract:ERC20 permit(EOA,コントラクトアドレス,トークンID,deadline,v,r,s)
                    MarketSmartContract->>MarketSmartContract:ERC20 approve(所有者アドレス、SmartContractMarketアドレス、トークンID)
                    MarketSmartContract-->>PostOrderFormUI: 出品成功
                    PostOrderFormUI-->>Seller: 出品登録成功通知
                    PostOrderFormUI-->MarketUI: 出品情報の表示
                end
        end
    end

